[[cells]]
name = "pausable-udt"
enable_type_id = true
location = { file = "build/release/pausable-udt" }

# The lock script set to output cells
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x66cbd102918e1c31578a6c6e35045539bb55b5ae"
hash_type = "type"